<?php
/**
 * Copyright © 2016 Czone Technologies. All rights reserved.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 * @var $filterItems CzoneTech\ImprovedCatalogSearch\Model\Layer\Filter\Item[]
 */
?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <?php
                $values = $filterItem->getFilterValues();
                if(!$values){
                    $values = [];
                }else if(!is_array($values)){
                    $values = [$values];
                }
                $checked = in_array($filterItem->getValue(), $values)? true: false;
                $uniqueId = 'filter_'.$filterItem->getFilter()->getRequestVar().'_'.$filterItem->getValue();?>
                <input id="<?php echo $uniqueId;?>" type="checkbox" <?php if($checked):?>checked="checked"<?php endif;?>
                onchange="javascript:window.location.href='<?php
                echo
                $block->escapeUrl
                ($filterItem->getUrl()) ?>';">
                <label for="<?php echo $uniqueId;?>">
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </label>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
